server:
  port: 8884
  contextPath: /order-service
  address: 0.0.0.0


spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://47.110.46.159:3306/order?useUnicode=true&characterEncoding=utf8
    username: root
    password: rootpassword
    initialSize: 20
    minIdle: 20
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  application:
    name: order-service

mybatis:
  type-aliases-package: com.github.steven.order.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: info


  path: "./logs"

inventory-service:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0

account-service:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0